import Head from 'next/head'
import { useState, useEffect } from 'react'

export default function Home() {
  const [users, setUsers] = useState([])

  useEffect(() => {
    const getUsers = async() => {
      await fetch("http://127.0.0.1:8080/user/get")
      .then(res => res.json())
      .then(data => {
          console.log(data)
      })
    }
    getUsers()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>

      </div>  
    </>
  )
}
